### ISSUE TITLE
[1.6.0b5] Sample Loader preview volume

### ISSUE THREAD

**Issue by PRAYTHEPO** [polyend/TrackerBetaTesting#1537]
Guys, pls, fix this distorted peaking volume in Sample Loader.

*If this was mentioned in any request before, sorry. I just almost blown my ears a moment ago.*

As i can see, preview of samples is going directly to Master, because Master Volume affects preview. Why not lower the volume for around -10dB while previewing? Really, it hurts ears.

**Comment by Jacknametrouble** [comment]
This topic was touched on and explained here plenty of times. Unfortunately, we don't have enough time to explain this case every single time. The volume is dependable on the instrument properties. There's not much that can or will be done about this, mostly due to the initial firmware assumptions. Best,
