### ISSUE TITLE
Simple waveform generator in Sample Recorder

### ISSUE THREAD

**Issue by bmuessig** [polyend/TrackerBetaTesting#1544]
It would be absolutely amazing for sample production, if these two things could be added:
1. A virtual input in the sample recorder that records nothing (Ground coupling)
2. Three filters in the sample editor that generate and mix-in sine, triangle and square-wave.

All three filters would have the properties amplitude and frequency. The square wave would also come with a duty-cycle.
These effects would then be applied to the selected region of the sample just like any other effect.

The ground coupling comes in useful to provide a blank canvas to mix sounds on. It allows to just generate an empty sample of the given length (and is a cleaner solution than disconnecting and sampling from an input).
Onto the (empty) sample, waveforms could then be added and mixed into each other (each filter mixes-in the sounds at the given amplitude).

It might also make sense to add a modulation mode (yes/no toggle) that scales the selection by the waveform to shape the selection e.g. for additive synthesis.

Being able to generate and mix sine, triangle and square-waves of different frequencies and volumes would be very useful and should not be too much work to implement. This would allow creating new sounds on the go and make the groove-box even more groovy :-)

**Comment by FelixCoffee** [comment]
That would be awesome!!! :D

**Comment by bmuessig** [comment]
After some reconsideration (and rightful advice on Reddit), I don't think anymore that this is the way to go for sample alteration/production. I've bought another synth for that now and will look into getting the tracker working with it then (that makes me wonder if the Tracker can trigger notes on another synth over MIDI while sample recoding).
I'm coming from the software and hardware side with only about 1.5 years worth of piano lessons but great interest in getting to know music production, so I'm still in the right place for silly feature requests :-)

**Comment by theorize999** [comment]
yes you can trigger notes on another synth while recording a sample, I haven't had much time for tracking for quite a while but last time I checked it still worked great, this is actually my favorite feature they implemented.... I would have had to sell mine otherwise. This is actually the beauty of tracking.. so yes go for it. It's really fun. You just can't trigger a pattern and sample at the same time you'll have to go for the midi press. If I remember right you can even use an external midi keyboard connected to the tracker and running from the tracker's midi out to your synth, don't take the last one as word I might be mixed up on that one. but the on board keys work just fine for sampling your synth. you can even go one further and create layered patches of your synth by putting equal notes in a pattern of your recorded samples and then resampling that, i reccoment using the note c for all this but do what you want, if you want sample accurate interpolation then at 16 bits 44k resolution sample the note G but honestly C works fine and is way easier to set up. happy tracking.

**Comment by bmuessig** [comment]
Thank you @theorize999 for your helpful explanation
